/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
    alert($(this).text());
});

var c = function (f) {
  return Math.round((f-32)*5/9);
}

var pic =function(condition,location){
  if (condition.search("Cloudy")>-1){
      skycons.set(location, Skycons.PARTLY_CLOUDY_DAY);
  } else if(condition.search("Thunderstorms")>-1){
      console.log()
      skycons.set(location, Skycons.RAIN);
  } else if(condition.search("Showers")>-1){
      skycons.set(location, Skycons.SLEET);
  } else {
      skycons.set(location, Skycons.CLEAR_DAY);
  }
}

var url =function (city) {
  return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22nome%2C%20"+city+"%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
}
$(".dropdown-menu>li>a").click(function () {
  var endpoint= url($(this).attr("cityName"));
  $("button").text($(this).children(".city").text());
  json(endpoint);
})

$("button").click(function () {
  $(".dropdown-menu>li>a").each(function (index, element) {
    $.getJSON(url($(element).attr("cityName")),function (data) {
      $(element).children(".cel").text(c(data.query.results.channel.item.condition.temp));
    })

    
  })
})


var json = function (url) {
  // "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22nome%2C%20Taipei%20City%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"
  $.getJSON(url,function(data){
    $(".temperature").text(c(data.query.results.channel.item.condition.temp));
    $(".date").text(data.query.results.channel.item.forecast[0].date);
    $(".description").text(data.query.results.channel.item.condition.text);
    $(".table tr>th:first-of-type").text(data.query.results.channel.item.forecast[1].date);
    $(".table tr>th:nth-of-type(2)").text(data.query.results.channel.item.forecast[2].date);
    $(".table tr>th:nth-of-type(3)").text(data.query.results.channel.item.forecast[3].date);
    $(".temp> td:first-of-type").text(c(data.query.results.channel.item.forecast[1].low) +" - "+c(data.query.results.channel.item.forecast[1].high)+" ℃ ");
    $(".temp> td:nth-of-type(2)").text(c(data.query.results.channel.item.forecast[2].low) +" - "+c(data.query.results.channel.item.forecast[2].high)+" ℃ ");
    $(".temp> td:nth-of-type(3)").text(c(data.query.results.channel.item.forecast[3].low) +" - "+c(data.query.results.channel.item.forecast[3].high)+" ℃ ");
    pic(data.query.results.channel.item.condition.text,"today");
    pic(data.query.results.channel.item.forecast[1].text,"day1");
    pic(data.query.results.channel.item.forecast[2].text,"day2");
    pic(data.query.results.channel.item.forecast[3].text,"day3");
  });
}

json(url("Taipei City"));

